@startuml C4_Elements
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
LAYOUT_TOP_DOWN
LAYOUT_WITH_LEGEND()

Person(userRegistration, "UserRegistration")
Person(userNotifier, "UserNotifier")
Person(userModel, "UserModel")
Person(db, "DB")
Person(connectionPool, "ConnectionPool")
Person(dbConfig, "DBConfig")

Rel(userRegistration,userNotifier," ")
Rel(userRegistration,userModel," ")
Rel(userModel,db," ")
Rel_R(db,connectionPool," ")
Rel_R(connectionPool,dbConfig," ")
@enduml